# Artificial Neural Network

### Importing Liberaries

In [16]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler 
from sklearn.model_selection import train_test_split

## Data preprocessing

#### Importing Dataset

In [11]:
df = pd.read_csv('../Data/P1-ANN/Churn_Modelling.csv')
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

### Encoding Categorical data

#### Label Encoding the "Gender" column

In [12]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

#### One-Hot Encoding Of Geography

In [13]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output= False), [1])], remainder= 'passthrough')
X = ct.fit_transform(X)

In [14]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


#### Splitting the Dataset into the training and testing set

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state= 42, stratify= y)

#### Feature Scaling

In [17]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN

#### Initializing the ANN

In [20]:
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN