# Artificial Neural Network

### Importing Liberaries

In [16]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

## Part-1 Data preprocessing

#### Importing Dataset

In [17]:
df = pd.read_csv('../Data/P1-ANN/Churn_Modelling.csv')
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

### Encoding Categorical data

#### Label Encoding the "Gender" column

In [18]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

#### One-Hot Encoding Of Geography

In [21]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder= 'passthrough')
X = np.array(ct.fit_transform(X))

In [22]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]
