# Artificial Neural Network

### Importing Liberaries

In [11]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler 
from sklearn.model_selection import train_test_split

## Data preprocessing

#### Importing Dataset

In [12]:
df = pd.read_csv('../Data/P1-ANN/Churn_Modelling.csv')
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

### Encoding Categorical data

#### Label Encoding the "Gender" column

In [13]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

#### One-Hot Encoding Of Geography

In [14]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output= False), [1])], remainder= 'passthrough')
X = ct.fit_transform(X)

In [15]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


#### Splitting the Dataset into the training and testing set

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state= 42, stratify= y)

#### Feature Scaling

In [17]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN

#### Initializing the ANN

In [18]:
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# For non binary we will use softmax activation function 

## Training the ANN

In [19]:
ann.compile(optimizer = "adam", loss = 'binary_crossentropy', metrics = ['accuracy'])
# this is for binary and for non binary we will categorical_crossentropy 

ann.fit(X_train, y_train, batch_size= 32, epochs= 100)


Epoch 1/100


235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 667us/step - accuracy: 0.6691 - loss: 0.6546
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.7960 - loss: 0.5127
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 662us/step - accuracy: 0.7969 - loss: 0.4608
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 679us/step - accuracy: 0.8108 - loss: 0.4235
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 622us/step - accuracy: 0.8240 - loss: 0.4001
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 615us/step - accuracy: 0.8357 - loss: 0.3870
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - accuracy: 0.8408 - loss: 0.3780
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - accuracy: 0.8443 - loss: 0.3712
Epoch 9/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - accuracy: 0.8457 - loss: 0.3664
Epoch 10/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - accuracy: 0.8483 - loss: 0.3631
Epoch 11/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 627us/step - accuracy: 0.8477 - loss: 0.3600
Epoch 12/100
235/235 ━━━━━━━━━━

#### Predicting the Single Observation

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

WIll the customer leave ??

In [24]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[False]]
