# Artificial Neural Network

### Importing Liberaries

In [23]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler 
from sklearn.model_selection import train_test_split

## Data preprocessing

#### Importing Dataset

In [24]:
df = pd.read_csv('../Data/P1-ANN/Churn_Modelling.csv')
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

### Encoding Categorical data

#### Label Encoding the "Gender" column

In [25]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

#### One-Hot Encoding Of Geography

In [26]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output= False), [1])], remainder= 'passthrough')
X = ct.fit_transform(X)

In [27]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


#### Splitting the Dataset into the training and testing set

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state= 42, stratify= y)

#### Feature Scaling

In [29]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN

#### Initializing the ANN

In [30]:
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# For non binary we will use softmax activation function 

## Training the ANN

In [31]:
ann.compile(optimizer = "adam", loss = 'binary_crossentropy', metrics = ['accuracy'])
# this is for binary and for non binary we will categorical_crossentropy 

ann.fit(X_train, y_train, batch_size= 32, epochs= 100)


Epoch 1/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 671us/step - accuracy: 0.5528 - loss: 0.7345
Epoch 2/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 667us/step - accuracy: 0.7971 - loss: 0.4901
Epoch 3/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 628us/step - accuracy: 0.8047 - loss: 0.4533
Epoch 4/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 636us/step - accuracy: 0.8143 - loss: 0.4313
Epoch 5/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - accuracy: 0.8233 - loss: 0.4188
Epoch 6/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - accuracy: 0.8297 - loss: 0.4103
Epoch 7/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 654us/step - accuracy: 0.8332 - loss: 0.4031
Epoch 8/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 641us/step - accuracy: 0.8359 - loss: 0.3963
Epoch 9/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 624us/step - accuracy: 0.8391 - loss: 0.3894
Epoch 10/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - accuracy: 0.8412 - loss: 0.3818
Epoch 11/100
235/235 ━━━━━━━━━━━━━━━━━━━━ 0s 637us/step - accuracy: 0.8464 - loss: 0.3753
Epoch 12/100
235/23